language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
	- npm install -g coffee-script
	- npm install -g less
	- gem install sass
    - phpenv rehash

install:
    - composer self-update
    - composer install --dev

script:
  - phpunit

notifications:
  email: false