language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - npm install -g coffee-script@1.9.2
  - npm install -g less@2.5.1
  - rvm use 2.1.0 --install --binary --fuzzy
  - PATH="$(ruby -rubygems -e 'puts Gem.user_dir')/bin:$PATH"
  - sudo ln -s `which ruby_executable_hooks` /usr/bin/ruby_executable_hooks
  - gem install sass -v 3.4.14
  - phpenv rehash

install:
  - composer self-update
  - composer install --dev

script:
  - phpunit

notifications:
  email: false